language: python
dist: xenial

stages:
  - lint
  - test

matrix:
  include:
    - python: 2.7
      env: TOXENV=flake8
      stage: lint

    - python: 3.8
      env: TOXENV=py3flake8
      stage: lint

    - python: 2.7
      env: TOXENV=py27
      stage: test

    - python: 3.6
      env: TOXENV=py36
      stage: test

    - python: 3.7
      env: TOXENV=py37
      stage: test

    - python: 3.8
      env: TOXENV=py38
      stage: test

    - python: 3.9
      env: TOXENV=py39
      stage: test
      
    - python: nightly
      env: TOXENV=py310
      stage: test

    - python: pypy
      env: TOXENV=pypy
      stage: test

    - python: pypy3.5
      env: TOXENV=pypy35
      stage: test

  allow_failures:
    - python: nightly

before_install:
  - pip install codecov
install:
  - pip install tox
script:
  - tox
after_success:
  - codecov
