name: "Deploy to PyPI"
on:
  workflow_dispatch:
    inputs: 
      tag:
        description: "Git tag to deploy to PyPI"
        required: true

jobs:
  deploy:
    name: "Deploy to PyPI"
    runs-on: ubuntu-latest
    environment: Deploy
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag }}
      - uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - shell: bash
        run: |
          python -m pip install --disable-pip-version-check -U pip
          python -m pip install -U setuptools wheel twine
          python setup.py sdist bdist_wheel
          python -m twine check dist/*
          python -m twine upload --username=__token__ --password=${{ secrets.PYPI_TOKEN }} dist/*
